/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_com_actia_platform_fms
#define DBUS_GLIB_CLIENT_WRAPPERS_com_actia_platform_fms

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_actia_platform_fms_service_state (DBusGProxy *proxy, gboolean* OUT_state, GError **error)

{
  return dbus_g_proxy_call (proxy, "ServiceState", error, G_TYPE_INVALID, G_TYPE_BOOLEAN, OUT_state, G_TYPE_INVALID);
}

typedef void (*com_actia_platform_fms_service_state_reply) (DBusGProxy *proxy, gboolean OUT_state, GError *error, gpointer userdata);

static void
com_actia_platform_fms_service_state_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gboolean OUT_state;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_BOOLEAN, &OUT_state, G_TYPE_INVALID);
  (*(com_actia_platform_fms_service_state_reply)data->cb) (proxy, OUT_state, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_actia_platform_fms_service_state_async (DBusGProxy *proxy, com_actia_platform_fms_service_state_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "ServiceState", com_actia_platform_fms_service_state_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_com_actia_platform_fms */

G_END_DECLS
